[phases.setup]
cmds = [
    "pip install -r requirements.txt",
]

[phases.install]
cmds = [
    "python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn taskflow.wsgi:application"
